### ISSUE TITLE
Problems when loading an old Hamiltonian

### ISSUE THREAD

**Issue by wsennane** [myQLM/myqlm-fermion#7]
Hello,

We had problems when loading an old Hamiltonian (ElectronicStructureHamiltonian object) with the new version of the QLM :

-	First, when loading the file (with pickle) :  ModuleNotFoundError: No module named 'qat.dqs'
-	We tried tackling this error with telling to python to load ‘qat.fermion’ instead of ‘qat.dqs’ if needed.
-	However, the loaded ElectronicStructureHamiltonian is not compatible with the new class (impossible to be printed, impossible to use the methods of ElectronicStructureHamiltonians). 

Would you mind helping us with this issue ? You will see the old Hamiltonian and the script here :
[problem_with_update.zip](https://github.com/myQLM/myqlm-fermion/files/11180012/problem_with_update.zip)

**Comment by m0liva** [comment]
Hello,

Your issue seems to stem from how `pickle` serializes data rather than it being a `myqlm-fermion` compatibility issue.

Since the data have been generated using the `qat.dqs` module, the Pickle serialization will look for the same class structure when loading the pickled file. But this structure has changed between `qat.dqs` and `qat.fermion`. Your way of circumventing this using the `sys` module is fine, only the data need to be accessed differently.

Since Pickle ultimately saves the object `__dict__`, you can access the old Hamiltonian attributes via this `__dict__` object directly.

Here is a little script to convert your data to the new `qat.fermion.ElectronicStructureHamiltonian`.

```python
# Import your data in obs_dict
import sys
import qat.fermion
import pickle

sys.modules['qat.dqs'] = qat.fermion
with open("LiH_dist.H.pickle", "rb") as file:
    obs_dict = pickle.load(file)

# Define a few helper functions to navigate and update the data dictionary more easily
from functools import reduce
import operator

def get_keys(obj):
    if isinstance(obj, dict):
        for k, v in obj.items():
            for keys in get_keys(v):
                yield [k] + keys
    else:
        yield []
        
def get_value(data, lst):
    return reduce(operator.getitem, lst, data)

def set_value(data, lst, value):
    get_value(data, lst[:-1])[lst[-1]] = value

# Convert the qat.dqs classes into qat.fermion classes
from qat.fermion import ElectronicStructureHamiltonian

for idx, k in enumerate(get_keys(obs_dict)): # Iterate over the different sets of keys
    if k[-1] == "H_active":
        
        # Read value at key in dictionary
        H = get_value(obs_dict, k)
        
        # Extract __dict__ data and update dictionary with new qat.fermion ElectronicStructureHamiltonian
        set_value(obs_dict, k, ElectronicStructureHamiltonian(hpq=H.__dict__["hpq"],hpqrs=H.__dict__["hpqrs"], constant_coeff=H.__dict__["_constant_coeff"].get_value()))
                  
# Check new Hamiltonians are now accessible and operable
print(obs_dict["0.4"]['sto-3g']['2']['4']['H_active'].to_fermion())
```

This should update your `qat.dqs` pickled data to `qat.fermion`.

Let me know if that solved your issue.

Have a nice day !
Maxime

**Comment by wsennane** [comment]
Thanks for your answer, it is working now

**Comment by m0liva** [comment]
Great, I am closing the issue.

Best,
Maxime

**Comment by tayral** [comment]
@wsennane can we close the issue?
